route53.tf

Blocked by https://github.com/femiwiki/femiwiki/issues/93

Make Route53 ignore ALB

---

github/github.tf

Resolves https://github.com/femiwiki/infra/issues/10
Terraform cloud check 잘 되나 볼려고 시범적으로 PR로 만들었습니다.

Change color of some labels

---

aws/cloudwatch.tf
aws/sns.tf

Resolves https://github.com/femiwiki/femiwiki/issues/119

Create Cloudwatch alarms

---

aws/ec2.tf

Resolves https://github.com/femiwiki/infra/issues/17

Use ignore_changes to Avoid hardcoding of AMI ID

---

aws/cloudwatch.tf
aws/ec2.tf
aws/iam.tf
aws/sg.tf

https://github.com/femiwiki/femiwiki/issues/117 관련 작업 중 일부
Blocked by https://github.com/femiwiki/docker-mediawiki/pull/312

Launch a new instance

---

aws/route53.tf

Blocked by https://github.com/femiwiki/infra/pull/15

 Change route 52 record to the new instance

---

aws/iam.tf

Closes https://github.com/femiwiki/infra/issues/22

Revert "Remove resources for Packer"

---

aws/s3.tf

aws_s3_bucket 타입으로 file validator bucket을 생성함

테스트용 File validator 버킷 추가

---

github/repo.tf

Related to https://github.com/femiwiki/femiwiki/issues/90

github: Create repository remote-gadgets

---

aws/ec2.tf
aws/res/bootstrap.sh

Closes https://github.com/femiwiki/femiwiki/issues/161

Mount a volume for k3s state

---

aws/route53.tf

Bing...에서 트래픽이 얼마나 들어오는진 모르겠지만 일단 츄라이 츄라이 하는 느낌으로 넣어 봅니다.
참조: femiwiki/femiwiki#173

Bing 검색 엔진 관리 등록

---

github/repo.tf

Closes #46, Ref femiwiki/femiwiki#69
참조: https://www.terraform.io/docs/providers/github/r/branch_protection.html#enforce_admins

관리자도 코드 리뷰 받도록 강제

---

.github/workflows/format.yml
github/repo.tf
terraform-cloud/base.tf

Closes https://github.com/femiwiki/infra/issues/33

Introduce terraform validate and fmt

---

github/team.tf

Reviewer 팀을 새로 만듭니다.
멤버는 수동으로 추가할 예정입니다.

github: Create a team

---

github/repo.tf

팀을 대상으로 리뷰를 요청하기 위해서는 리포들을 팀과 연결할 필요가 있는 것 같으며 이에 따라 연결합니다.
지금 이 리포는 테스트 차 연결한 뒤 `terraform import` 한 상태입니다.

Add github_team_repository resources

---

github/project.tf

Workaround 컬럼을 추가합니다. 현재 Blocked에
1. 다른 이슈에 막혀 진짜 해결을 못 하는 이슈
2. 아직 릴리즈 되지 않은 버전에 대한 업데이트 등 당장 못 하는 것들
3. 대충 해결했지만 업스트림이 패치되면 Workaround를 빼야 하는 것들
이 섞여 있는데 3번을 위한 컬럼입니다.

project.tf: Add column Workaround

---

github/repo.tf

Add an emoji to the description of Sanction repo

---

aws/ec2.tf

Related to https://github.com/femiwiki/infra/issues/56
Merge 및 run은 해당 이슈에 적힌 점검 시나리오에 따라 실행할 예정입니다

Changing the Instance type to t3a.small

---

aws/route53.tf

https://github.com/femiwiki/femiwiki/issues/173 Google Search Console TXT 레코드를 추가합니다.
제대로 한 건지 잘 모르겠습니다 잘못되었으면 수정해 주세요~
References:
- https://support.google.com/webmasters/answer/34592
- https://support.google.com/webmasters/answer/9008080
- https://www.terraform.io/docs/providers/aws/r/route53_record.html

route53: Add a record for Google Search Console

---

aws/ec2.tf
aws/res/bootstrap.sh

바로 적용하고싶지만 `mkfs -t xfs /dev/xvdf` 를 해줘야해서 일단 Draft PR로 올립니다

Change persistent data location

---

github/repo.tf

봇들이 만드는 브랜치를 삭제하기 번거로워서 자동 삭제 설정을 켤까 합니다

github: Delete branch on merge at docker-mediawiki

---

github/repo.tf

Related to https://github.com/femiwiki/femiwiki/issues/204

github: Create .github repository

---

github/repo.tf

Related to https://github.com/femiwiki/femiwiki/issues/116

Create new repository "nomad"

---

aws/base.tf
github/base.tf

Migrate to Terraform v0.13

---

aws/base.tf
aws/ec2.tf

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade

Bump AWS Provider to Version 3

---

aws/ec2.tf
aws/res/bootstrap.sh

k3s 대신 Docker와 Nomad와 Consul을 깔고 systemctl로 시작시키고 femiwiki/nomad 리포도 받아놓고 합니다.
Related to https://github.com/femiwiki/femiwiki/issues/116

Prepare Nomad on aws_instance.femiwiki_green

---

aws/base.tf
github/base.tf

https://github.com/femiwiki/femiwiki/issues/243

Bump Terraform to v0.15.0

---

aws/iam-policies.tf
aws/iam.tf
aws/s3.tf

https://github.com/femiwiki/nomad/issues/18

Create a bucket and IAM policies for secrets

---

aws/ec2.tf

https://github.com/femiwiki/femiwiki/issues/245

Make the main domain directed to the t4g instance

---

aws/ec2.tf
aws/res/bootstrap-consul.sh

Related to https://github.com/femiwiki/nomad/issues/21

aws: Launch test instances for consul

---

github/label.tf

https://github.com/femiwiki/femiwiki/issues/289

gh: Remove labels of DiscordNotifications

---

aws/route53.tf

https://github.com/femiwiki/femiwiki/issues/173

aws: Add Yandex Webmaster verifying TXT record

---

aws/cloudwatch.tf
aws/res/bootstrap.sh

aws: Remove a not working cloudwatch alarm

---

aws/iam-policies.tf
aws/iam.tf

Related to https://github.com/femiwiki/lambda/issues/32

aws: Add github_lambda IAM user and a policy

---

aws/ec2.tf
aws/outputs.tf

This is firstly for https://github.com/femiwiki/nomad/issues/99, but can also be used generally in the future.

aws: Make it easy to launch a test server

---

aws/cloudwatch.tf

Disable VolumeIdleTime alarm

---

aws/route53.tf

이게 왜 여기서 255 char limit;;
살짝졸려서 암데서나대충짤랐는데 이래도실패하면 내일마저볼게요,,,
Ref femiwiki/femiwiki#172
Ref hashicorp/terraform-provider-aws#14941

Terraform error

---

aws/route53.tf

Fixes femiwiki/femiwiki#172
DMARC 리포트의 raw값을 보기-좋게 포장해서 공동메일함으로 쏴 줍니다.

DMARC record

---

aws/ec2.tf
aws/res/bootstrap.sh
aws/res/vector.toml

https://github.com/femiwiki/femiwiki/issues/344

Install and start Vector agent

---

aws/res/bootstrap.sh

dmidecode is a requirement of Nomad

aws: Install dmidecode

---

github/modules/github-repository/main.tf

gh: Disable discussions

---

github/label.tf

- gh: Cleanup labels
- label: Add 'help_wanted'

Github: Add 'help_wanted' label

---

aws/ec2.tf
aws/res/bootstrap.sh

- **aws: Configure CWAgent**
- **aws: Sort alphabetically and use user_data_replace_on_change**
- **aws: Remove LICENSE file in bin directory**

Improve test server

---

aws/res/bootstrap.sh

- **aws: Disable dnsmasq**
- **aws: Improve bootstrap.sh**

Configure test server

---

aws/ec2.tf
aws/res/bootstrap.sh

https://github.com/femiwiki/nomad/issues/21

aws: Use systemd-resolved instead of dnsmasq

---

github/repo-extension.tf

https://github.com/femiwiki/UnifiedExtensionForFemiwiki/issues/172

github: Do not protect the branches of UnifiedExtensionForFemiwiki

---

aws/res/consul.hcl
aws/res/user-data.sh.tftpl

Maybe related to https://github.com/femiwiki/nomad/issues/8

Install Nomad and Consul using hashicorp repo

---

aws/res/user-data.sh.tftpl

https://github.com/femiwiki/nomad/issues/8

Make 127.0.0.1:53 redirected to 127.0.0.1:8600

---

aws/ec2.tf
aws/outputs.tf
aws/res/user-data.sh.tftpl

https://github.com/femiwiki/femiwiki/issues/253

Launch the second test server

---

aws/ec2.tf
aws/res/consul.hcl
aws/res/user-data.sh.tftpl

Closes https://github.com/femiwiki/nomad/issues/296

consul: Name is not required

---

aws/res/consul.hcl
aws/res/nomad.hcl

https://github.com/femiwiki/femiwiki/issues/253

nomad: Make bootstrap expect 2

---

aws/ec2.tf
aws/outputs.tf

aws: Create persistent_data_caddycerts_green

---

aws/ec2.tf
aws/iam-policies.tf
aws/outputs.tf

https://github.com/femiwiki/femiwiki/issues/372

aws: Create an EBS volume for MySQL replica

---

aws/ec2.tf
aws/iam-policies.tf
aws/outputs.tf

Revert "aws: Create an EBS volume for MySQL replica"

---

aws/ec2.tf
aws/res/nomad.hcl

closes https://github.com/femiwiki/femiwiki/issues/373

aws: Add custom meta to the first instance

---

aws/ec2.tf
aws/res/nomad.hcl.tftpl

- Add readable name
- Three nodes are the minimum requirement.
- Closes https://github.com/femiwiki/infra/issues/349

aws: Improve nomad.hcl

---

aws/res/config.alloy.tftpl

https://github.com/femiwiki/infra/issues/352

aws: Add alloy metrics

---

aws/cloudwatch.tf

https://github.com/femiwiki/femiwiki/issues/379

aws: Change datapoints to 4 out of 8

---

aws/res/config.alloy.tftpl
aws/res/nomad.hcl.tftpl
aws/res/user-data.sh.tftpl

https://github.com/femiwiki/femiwiki/issues/344

alloy: Add docker logs

---

aws/cloudwatch.tf

Revert "aws: Change datapoints to 4 out of 8"

---

aws/route53.tf

route53: Add atproto DNS

---

github/repo-extension.tf

github: do not require selenium tests

---

github/label.tf

https://github.com/femiwiki/femiwiki/issues/401

github: Remove bug label

---

aws/cloudwatch.tf
aws/route53.tf

Special:BlankPage is uncacheable while the main page is cacheable.

aws: Add a check for Special:BlankPage

---

aws/iam.tf
aws/iam_instance_profile.tf
aws/sg.tf

Closes https://github.com/femiwiki/femiwiki/issues/414

aws: Create security groups for mediawiki-mysql relationship

---

aws/ebs.tf
aws/ec2.tf
aws/iam.tf
aws/iam_instance_profile.tf
aws/res/user-data-mysql.sh.tftpl
aws/sg.tf

https://github.com/femiwiki/femiwiki/issues/415

aws: Launch a dedicated MySQL server

---

aws/ebs.tf
aws/ec2.tf
aws/res/user-data-mysql.sh.tftpl

https://github.com/femiwiki/femiwiki/issues/415

Mysql instance 2

---

aws/iam.tf
aws/res/user-data-mysql.sh.tftpl

aws: Fix policy attachment

---

aws/ebs.tf
aws/ec2.tf
aws/res/user-data-mysql.sh.tftpl

https://github.com/femiwiki/femiwiki/issues/415

aws: Fix mysql user data

---

aws/res/user-data-mysql.sh.tftpl

https://github.com/femiwiki/femiwiki/issues/415

aws: Find mysql pass when initializing only

---

aws/ec2.tf
aws/eip.tf
aws/outputs.tf

Closes https://github.com/femiwiki/femiwiki/issues/416

aws: change the target of femiwiki.com

---

docker/backend.tf

https://github.com/femiwiki/femiwiki/issues/416

docker: Update host
